name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker Image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/360-auth-backend:latest .

      - name: Push Docker Image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/360-auth-backend:latest

  deploy:
    needs: build
    runs-on: auth-ec2
    steps:
      - name: Pull Docker Image from Docker Hub
        run: sudo docker pull ${{ secrets.DOCKER_USERNAME }}/360-auth-backend:latest

      - name: Remove Old Container (if exists)
        run: |
          CONTAINER_ID=$(sudo docker ps -aq --filter "name=360-auth-backend")
          if [ -n "$CONTAINER_ID" ]; then
            sudo docker stop $CONTAINER_ID
            sudo docker rm -f $CONTAINER_ID
          fi

      - name: Run Docker Container
        run: |
          sudo docker run -d -p 5000:5000 \
          -e SECRET_KEY="${{ secrets.SECRET_KEY }}" \
          -e ENCRYPTION_KEY="${{ secrets.ENCRYPTION_KEY }}" \
          -e PRIVATE_KEY="${{ secrets.PRIVATE_KEY }}" \
          -e PUBLIC_KEY="${{ secrets.PUBLIC_KEY }}" \
          -e MAILGUN_API_KEY="${{ secrets.MAILGUN_API_KEY }}" \
          -e MAILGUN_DOMAIN="${{ secrets.MAILGUN_DOMAIN }}" \
          -e MAILGUN_API_URL="${{ secrets.MAILGUN_API_URL }}" \
          -e AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }} \
          -e AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }} \
          -e S3_BUCKET=${{ secrets.S3_BUCKET }} \
          -e S3_REGION=${{ secrets.S3_REGION }} \
          --name 360-auth-backend \
          ${{ secrets.DOCKER_USERNAME }}/360-auth-backend:latest

      - name: Check Container Status
        run: sudo docker ps
